# Generated by Django 5.1.1 on 2024-09-13 21:41

import deliveries.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=deliveries.models.get_delivery_image_upload_to)),
            ],
        ),
        migrations.CreateModel(
            name='IssuePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=deliveries.models.get_issue_photo_upload_to)),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal_year', models.CharField(max_length=4)),
                ('delivery_number', models.PositiveIntegerField()),
                ('client_conformity', models.BooleanField(default=True)),
                ('has_issue', models.BooleanField(default=False)),
                ('observations', models.TextField(blank=True, null=True)),
                ('issues', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivery_images', models.ManyToManyField(blank=True, to='deliveries.deliveryimage')),
                ('issue_photos', models.ManyToManyField(blank=True, to='deliveries.issuephoto')),
            ],
        ),
    ]
