# Generated by Django 5.1.1 on 2024-09-13 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='client_number',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='delivery',
            name='issues',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
