# Generated by Django 5.1.1 on 2024-09-14 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0002_delivery_client_number_alter_delivery_issues'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='is_resolved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='delivery',
            name='visit_type',
            field=models.CharField(choices=[('delivery', 'Entrega'), ('verification', 'Verificación'), ('resolution', 'Resolución')], default='delivery', max_length=20),
        ),
    ]
