# Generated by Django 5.1.1 on 2024-09-09 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0003_alter_delivery_issues'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='delivery_date',
        ),
        migrations.AlterField(
            model_name='delivery',
            name='issues',
            field=models.JSONField(default=list),
        ),
    ]
