# Generated by Django 5.1.1 on 2024-09-14 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0004_transportista'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transportista',
        ),
    ]
