# Generated by Django 5.1.1 on 2024-09-21 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0008_alter_transporter_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='transporter',
        ),
        migrations.DeleteModel(
            name='Transporter',
        ),
    ]
