# Generated by Django 5.1.1 on 2024-10-01 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0012_delivery_customer_alter_delivery_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_number', models.PositiveIntegerField(unique=True)),
                ('description', models.CharField(max_length=255)),
                ('supplier_number', models.PositiveIntegerField()),
                ('supplier_name', models.CharField(max_length=255)),
            ],
        ),
    ]
