# Generated by Django 5.1.1 on 2024-10-07 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0013_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='incident_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='status',
            field=models.CharField(blank=True, choices=[('pendiente_tratar', 'Pendiente de Tratar'), ('tratado_pendiente_resolucion', 'Tratado Pendiente de Resolución'), ('finalizado', 'Finalizado')], max_length=30),
        ),
    ]
