# Generated by Django 5.1.1 on 2024-10-11 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0014_delivery_incident_number_delivery_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryimage',
            name='delivery',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_image_set', to='deliveries.delivery'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='issuephoto',
            name='delivery',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='issue_photo_set', to='deliveries.delivery'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='delivery',
            name='delivery_images',
            field=models.ManyToManyField(blank=True, related_name='deliveries', to='deliveries.deliveryimage'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='issue_photos',
            field=models.ManyToManyField(blank=True, related_name='deliveries', to='deliveries.issuephoto'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.CharField(choices=[('pendiente_tratar', 'Pendiente de Tratar'), ('tratado_pendiente_resolucion', 'Tratado Pendiente de Resolución'), ('finalizado', 'Finalizado')], default='pendiente de tratar', max_length=30),
        ),
    ]
