# Generated by Django 5.1.1 on 2024-10-12 14:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0015_deliveryimage_delivery_issuephoto_delivery_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='products',
            field=models.ManyToManyField(to='deliveries.product'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.CharField(choices=[('pendiente_tratar', 'Pendiente de Tratar'), ('tratado pendiente resolucion', 'Tratado Pendiente de Resolución'), ('finalizado', 'Finalizado')], default='pendiente de tratar', max_length=30),
        ),
    ]
