# Generated by Django 5.1.1 on 2024-10-12 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0016_delivery_products_alter_delivery_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='products',
        ),
    ]
