# Generated by Django 5.1.1 on 2024-10-17 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0017_remove_delivery_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.CharField(choices=[('pendiente_tratar', 'Pendiente de Tratar'), ('tratado_pendiente_resolucion', 'Tratado Pendiente de Resolución'), ('finalizado', 'Finalizado'), ('no_resuelto', 'No Resuelto')], default='pendiente de tratar', max_length=30),
        ),
    ]
