# Generated by Django 5.1.1 on 2024-10-19 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0018_alter_delivery_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailnotificationfailure',
            name='albaran',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='emailnotificationfailure',
            name='email_type',
            field=models.CharField(blank=True, choices=[('albaran_incidencia', 'Albarán con Incidencia'), ('registro_incidencia', 'Registro de Incidencia'), ('resolucion_incidencia', 'Resolución de Incidencia')], max_length=50, null=True),
        ),
    ]
