# Generated by Django 5.1.1 on 2024-10-20 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0019_emailnotificationfailure_albaran_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailnotificationfailure',
            name='status',
            field=models.CharField(default='pendiente_contacto', max_length=20),
        ),
    ]
