# Generated by Django 5.1.1 on 2024-10-21 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0020_emailnotificationfailure_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailnotificationfailure',
            name='delivery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='deliveries.delivery'),
        ),
    ]
