# Generated by Django 5.1.1 on 2024-10-22 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0021_emailnotificationfailure_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='status_satisfaction',
            field=models.CharField(choices=[('no_tratado', 'No Tratado'), ('tratado', 'Tratado')], default='no_tratado', max_length=50),
        ),
    ]
